# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "efficient-logistics-app"
client_id = "972e35f7edf46af4d46168122882849a"
application_url = "https://efficient-logistics-app.onrender.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://efficient-logistics-app.onrender.com/auth/callback",
  "https://efficient-logistics-app.onrender.com/auth/shopify/callback",
  "https://efficient-logistics-app.onrender.com/api/auth/callback",
  "https://efficient-logistics-app.onrender.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "eshipz-edd-test.myshopify.com"
